services:
  studentprogress-api:
    image: henriqueaze/studentprogress:latest
    container_name: studentprogress-api
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "8080:8080"
    networks:
      - studentprogress-net

networks:
  studentprogress-net:
    driver: bridge
