CREATE TABLE IF NOT EXISTS students (
  id BIGSERIAL PRIMARY KEY,
  birth_date VARCHAR(255) NOT NULL,
  class VARCHAR(255) NOT NULL,
  course VARCHAR(255) NOT NULL,
  cpf VARCHAR(255),
  email VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  notes BYTEA NOT NULL,
  registration VARCHAR(255) NOT NULL
);
